name: automerge-label
on:
  pull_request_target:
    types:
      - opened
jobs:
  automerge-label:
    runs-on: ubuntu-latest
    name: automerge-label
    if: ${{ github.actor == '' }}
    steps:
      - uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: automerge
